### ISSUE TITLE
requests.session ignores second `verify` argument?

### ISSUE THREAD

**Issue by hjwp** [requests/requests#4391]
Am doing some testing for HTTPS certificates, and am seeing some unexpected behaviour from the requests "session" object:

```
import requests
# www.ottg.eu has a known invalid https certificate:
requests.session().get('https://www.ottg.eu', verify=True)
# raises error as expected

session = requests.session()
session.get('https://www.ottg.eu', verify=False)
# as expected does not raise, prints InsecureRequestWarning, 

session.get('https://www.ottg.eu', verify=True)
# unexpectedly, this seems to ignore the verify parameter, and it does not raise
# it also still prints the InsecureRequestWarning
```

That doesn't seem right?

tested against requests 2.18.4 on ubuntu 17.10

**Comment by hjwp** [comment]
(just repro'd in both python2 and python3, and on windows)

**Comment by hjwp** [comment]
maybe this is expected behaviour?  because of connection pooling?

**Comment by hjwp** [comment]
(with apologies for the stream-of-consciousness) -- it definitely is because of connection pooling, isn't it.  behaviour surprising but maybe not unexpected after all?  i suppose a fix would be to somehow keep track of connections and changes in the `verify` argument?    probably quite a heavyweight fix for an edge case...

**Comment by sigmavirus24** [comment]
We started working on a fix for this but it took us down a deep and very dark rabbit hole that led to very bad places if I remember correctly. I think the PR might still be open on urllib3 but I don't think it's advisable. A similar yet different solution might be to have two `https://` connection pools in an adapter one for verified connections and one for unverified connections to hack around this ugly behaviour. (Or have a session with 3 httpadapters such that one adapter only ever handles unverified TLS connections. I think that's less elegant though)

**Comment by jeremycline** [comment]
I think this is fixed in proposed/3.0.0 with https://github.com/requests/requests/pull/3109 and https://github.com/requests/requests/pull/4173

**Comment by Lukasa** [comment]
Yup, this is fixed in 3.0.0 as I recall.

**Comment by nateprewitt** [comment]
Alright, I think we can close this out since it's fixed in the 3.0.0 branch and it doesn't seem like we have any action we can take to mitigate this in the 2.x branch.

**Comment by atzannes** [comment]
Looks like v3 is still not out over 2 years later, and I have a fix for this for v2 in PR #5406
